#!/bin/bash

# Saheli Store Setup Script

echo "========================================="
echo "Saheli Store - Setup Script"
echo "========================================="

# Step 1: Firebase Console Setup
echo ""
echo "📋 Step 1: Update Firestore Security Rules"
echo "-------------------------------------------"
echo "1. Go to Firebase Console: https://console.firebase.google.com"
echo "2. Select project: saheli1"
echo "3. Navigate to: Firestore Database → Rules"
echo "4. Copy rules from: /app/FIRESTORE_RULES.md"
echo "5. Click 'Publish' to apply changes"
echo ""
read -p "Press Enter when rules are updated..."

# Step 2: Create Admin User
echo ""
echo "👤 Step 2: Create Admin User"
echo "-------------------------------------------"
echo "1. Run the app and register with:"
echo "   Email: admin@saheli.com"
echo "   Password: (choose a secure password)"
echo ""
echo "2. After registration, go to Firebase Console:"
echo "   → Firestore Database"
echo "   → users collection"
echo "   → Find the admin@saheli.com user document"
echo "   → Add field: 'role' with value 'admin'"
echo "   → Save"
echo ""
read -p "Press Enter when admin user is created..."

# Step 3: Verify Installation
echo ""
echo "✅ Step 3: Verify Installation"
echo "-------------------------------------------"
echo "All code files have been created!"
echo ""
echo "Created/Updated Files:"
echo "  • 4 Service files (product, cart, order, razorpay)"
echo "  • 3 Component files (ProductCard, CartItem, OrderCard)"
echo "  • 5 Admin screens (products, add, edit, orders, layout)"
echo "  • 5 Store screens (product-detail, cart, checkout, orders, layout)"
echo "  • 1 Main store tab screen"
echo "  • Updated navigation and user service"
echo ""

# Step 4: Test the App
echo ""
echo "🧪 Step 4: Test the Application"
echo "-------------------------------------------"
echo "To test the store feature:"
echo ""
echo "1. Start the app:"
echo "   cd /app"
echo "   yarn start"
echo ""
echo "2. Test User Flow:"
echo "   • Register/login as regular user"
echo "   • Navigate to 'Store' tab"
echo "   • Browse products"
echo "   • Add items to cart"
echo "   • Checkout (web only for Razorpay)"
echo ""
echo "3. Test Admin Flow:"
echo "   • Login with admin@saheli.com"
echo "   • Tap 'Admin' button in Store tab"
echo "   • Add/edit/delete products"
echo "   • View and manage orders"
echo ""

# Step 5: Documentation
echo ""
echo "📚 Step 5: Documentation"
echo "-------------------------------------------"
echo "Complete documentation available at:"
echo "  • /app/SAHELI_STORE_DOCUMENTATION.md"
echo "  • /app/FIRESTORE_RULES.md"
echo ""

# Completion
echo ""
echo "========================================="
echo "✨ Setup Complete!"
echo "========================================="
echo ""
echo "The Saheli Store feature is now fully integrated!"
echo ""
echo "For support, refer to:"
echo "  - Documentation: /app/SAHELI_STORE_DOCUMENTATION.md"
echo "  - Security Rules: /app/FIRESTORE_RULES.md"
echo ""
echo "Happy selling! 🛍️"
echo ""
